apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginWebDAV
spec:
  enabled: true
  version: 1.0.0
  requires: ">=2.19.0"
  author:
    name: Halo
    website: https://github.com/halo-dev
  logo: logo.svg
  settingName: webdav-settings
  configMapName: webdav-settings
  repo: https://github.com/knifezred/plugin-unsplash
  homepage: https://github.com/knifezred/plugin-unsplash
  issues: https://github.com/halo-sigs/plugin-unsplash/issues
  displayName: "WebDAV"
  description: "提供从 WebDAV 选择或转存图片的能力,根据plugin-unsplash修改"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/knifezred/plugin-unsplash/blob/main/LICENSE"